In [33]:
from bs4 import BeautifulSoup
import requests

In [34]:
url = 'https://www.datajob.io/'
page = requests.get(url)
soup = BeautifulSoup(page.text,'html')

In [35]:
divs = soup.find_all('div', class_='content_card-block')

In [36]:

job_names =[]
company_names=[]
job_descs =[]
job_infos= []
for div in divs:
    job_info_array =[]
    nested_div_job_name = div.find('div', class_='content_card-title')
    nested_div_job_name = nested_div_job_name.text.strip() 
    nested_div_company_name = div.find('div', class_='content_card-company-name')
    nested_div_company_name = nested_div_company_name.text.strip()
    nested_div_job_desc = div.find('div', class_='content-card-div-job-desc').text.strip()
    nested_div_job_info = div.find_all('div', class_='content_card-location-ff-salary')
    for job in nested_div_job_info:
        nested_div_job_info = job.find_all('div', class_='content_card-info-text')
        for job_info in nested_div_job_info:
            #print(job_info.text.strip())
            job_info_array.append(job_info.text.strip())
    
    #print(nested_div_job_name)
    #print(nested_div_company_name)
    #print(nested_div_job_desc)
    #print(nested_div_job_info)
    #print(nested_div_job_req)
    job_names.append(nested_div_job_name)
    company_names.append(nested_div_company_name )
    job_descs.append(nested_div_job_desc)
    job_infos.append(job_info_array)




    #break

In [37]:
print(job_names)
print("--------------------")
print(company_names)
print('-----------------------')
print(job_descs)
print('-------------------')
print(job_infos)

['Senior Data Analyst, Business Analytics (Supply Acquisition)', 'Applied Scientist (MT), ASIN Localization', 'AI Research Scientist', 'Data Analyst Supply Chain (m/w/d) - Gigafactory', 'Data Engineer - Partner Tech', 'Data Engineer, Amazon Deals', 'Data Scientist', 'Senior Data Analyst - Customer Experience Analytics (all genders)', 'Data Engineer', 'Data Engineer - Customer Fulfillment BI', 'Senior Data Engineer (Experimentation Platform)', 'Junior Data Scientist', 'Data Scientist', 'Sr. Pricing Data Scientist/Analyst', '(Senior) Data Analyst - Allianz Direct', 'Data Engineer - Zalando Marketing Services', 'Senior Applied Researcher', 'Business Intelligence Analyst', 'Data Analyst / Decision Scientist, Network', '(Junior) Data Engineer', 'Data Engineer', 'Data / ML Engineer - Performance Marketing', 'Data Scientist â\x80\x93 Bidding and Recommendations', 'Senior Data Analyst, Marketing/Measurement', 'Senior Data / Product Analyst in Performance Marketing', 'Data Engineer â\x80\x93 Content', 'Senior Applied Scientist - Customer Relationship Management (CRM)', 'Sr Data Engineer - CRM', 'Applied Researcher', 'Senior Data Analyst', 'Senior Data Scientist, Courier Earnings', 'Senior Data Scientist', 'Senior Data / Product Analyst in CRM / Customer Inbox', 'Data Engineer (F/M/D) - Marketing', 'Senior Data Engineer for Partner Tech', 'Research Scientist', 'Senior Data Scientist', 'Analytics Engineer (Data Governance) (m/f/d)', 'Data Engineer', 'Senior Data Engineer', 'Software / Machine Learning Engineer - Map Data', 'Data Engineer (Mid/Senior) - Machine Learning Engineering - Markets', 'Senior Big Data Engineer Hadoop & Cloud', 'Research Engineer - Automatic Speech Recognition', 'Senior Applied Scientist', 'Senior Data Engineer for Lounge by Zalando', '(Senior) Data Scientist - Credit Risk', 'Senior Applied Scientist - Marketing Services', 'Data Engineer - Demand Offer Data Platform - Markets', 'Senior Engineer in Data & Machine Learning', 'Imaging Scientist - Hardware Test Engineering Group', 'Senior Data Engineer - Experimentation Platform', '(Junior) Data Scientist', 'Junior Data Scientist', '(Senior) Analytics Engineer / Data Engineer', 'Senior Big Data Engineer', 'Senior Data Engineer', 'Senior Applied Scientist', 'Senior Applied Scientist', 'Applied Scientist (Marketing Intelligence)', 'Senior Data Scientist']
--------------------
['Get Your Guide', 'Amazon', 'Autodesk', 'Tesla', 'Zalando', 'Amazon', 'Billie', 'Zalando', 'Omio', 'Zalando', 'Get Your Guide', 'Adidas', 'DocMorris', 'Grover', 'Allianz', 'Zalando', 'eBay', 'adjoe', 'Vinted', 'home24', 'home24', 'Zalando', 'Trivago', 'Get Your Guide', 'Zalando', 'Trivago', 'Zalando', 'Zalando', 'eBay', 'SumUp', 'Wolt', 'Sixt', 'Zalando', 'IONOS', 'Zalando', 'DeepL', 'Microsoft', 'Omio', 'DeepL', 'Zalando', 'Lyft', 'Zalando', 'Deutsche Bank', 'SONY', 'Zalando', 'Zalando', 'home24', 'Zalando', 'Zalando', 'Zalando', 'Apple', 'Zalando', 'Check 24', 'Allianz Health Digital', 'TeamViewer', 'AMADEUS', 'epilot', 'Zalando', 'Zalando', 'Zalando', 'adjoe']
-----------------------
["*What you'll do: You will be focusing on uncovering opportunities and influencing the supply acquisition strategy.", "*What you'll do: You will focus on delivering optimal translation quality for product data at a massive scale.", "*What you'll do: You will be doing fundamental and applied research in AI.", "*What you'll do: You will be working on delivering process improvements, systems capabilities, and data insights for Direct Supply Chain components and materials team.", "*What you'll do: You will support the implementation of a reliable and performant data infrastructure that integrates with internal and 3rd party tools.", "*What you'll do: You will work closely with cross-functional teams to implement data pipelines, ETL processes, data modeling, and best practices.", "*What you'll do: You will be building and implementing fraud detection models across different portfolios.", "*What you'll do: You will be working with customer experience, extracting insights and translating them into actionable recommendations.", "*What you'll do: You will be working on maintaining and improving data ingestion platform.", "*What you'll do: You will be responsible for designing and implementing scalable data pipelines that are essential for supporting the expansion of the data warehouse.", "*What you'll do: You will design and implement features in the A/B experimentation platform with scalable and efficient data and software engineering practices.", "*What you'll do: You will be working on the recommendation algorithm improvements.", "*What you'll do: You will be working on smart/optimization/personalisation algorithms, recommender systems, forecasting and predictive models.", "*What you'll do: You will be working on building and improving pricing engine.", "*What you'll do: You will be part of Finance function at Allianz Directand provide key stakeholders with appropriate information, analyses and recommendations to steer the company on a value-based approach.", "*What you'll do: You will develop and further enhance Zalando's self-service web interfaces.", "*What you'll do: You will be working on the next generation of online advertising and search ranking products in eBay search.", "*What you'll do: You will be working on creating, analyzing and communicating reports and statistics for the business teams and partners.", "*What you'll do: You will be working on performance metrics for carrier portfolio, automation of carrier tracking, ways to optimise the services provided.", "*What you'll do: You will be working on designing, implementing and maintaining data processing pipelines in different clouds.", "*What you'll do: You will be working on designing, implementing and maintaining data processing pipelines in different clouds.", "*What you'll do: You will be working on Implementing and maintaining high-performance and growth-ready data-processing and data integration pipelines.", "*What you'll do: You will design, implement, and improve our bidding algorithms and evaluate their performance on live data.", "*What you'll do: You will be helping to improve and to create measurement tools to determine the ROI of the performance marketing campaigns.", "*What you'll do: You will ensure a consistent and sustainable channel performance and profitable growth.", "*What you'll do: You will process and deliver high quality content, by utilizing modern cloud technologies for batch and stream data processes.", "*What you'll do: You will analyse client behaviour and develop targeted communication strategies.", "*What you'll do: You will develop, monitor, and operate data integration pipelines, deployed as applications on a PaaS/SaaS cloud.", '*Ebay is a global e-commerce marketplace. You will work on such diverse projects as Image Quality scoring; Automatic Taxonomy Improvement and more.', '*SumUp is a top payments company in Germany. You will analyze data, create insights, and build user-friendly dashboards to support product research, strategy, and decision-making', '*Wolt is one of the largest food delivery services in Germany. You will be working on on developing algorithms and solutions to define pricing strategies for tasks completed by the couriers.', '*Sixt a leading global mobility service provider. You will be working on models that improve revenue management, demand forecast and more.', '*Zalando is a top e-commerce company in fashion retail in Germany. You will be working on sending the right message at the right time, be it information about a customerâ\x80\x99s purchase or a marketing message.', '*IONOS is the leading European provider of cloud infrastructure. You will be responsible for designing and maintaining our data warehouse to support the needs of the business.', '*Zalando is a top e-commerce company in fashion retail in Germany. You will get the opportunity to build a new data platform from the early stages together with the team.', '*DeepL is the go-to translation tool for fast, accurate and high-quality translations. You will conduct cutting-edge research on neural translation networks.', '*Microsoft is an American multinational technology corporation. You will be responsible for creating and deploying AI solutions.', '*Omio is a tool for comparing and combiningrail, air, bus, and car for destinations. You willdevelop and implement data governance strategies and processes, aligning them with the business strategies.', '*DeepL is the go-to translation tool for fast, accurate and high-quality translations. You will build and maintain data tables, libraries and the tooling supporting data processing at DeepL.', '*Sixt a leading global mobility service provider. You will automate operations, increase self-service capabilities (for ingestion, ETLs, and distribution), and enable new use cases for customers.', '*Lyft is an American company offering mobility as a service. You will work end-to-end on creating new capabilities to detect changes in the environment and reflect them in the Lyft map.', '*Zalando is a top e-commerce company in fashion retail in Germany. You will Design, develop and operate reliable data integration pipelines processing huge data volume.', "*What you'll do: Deutsche Bank is a global investment bank. You will be working on new features of the analytics platform.", "*What you'll do: You will develop and design prototypes of novel DNN based generative audio algorithms, prototypes of algorithms for automatic speech recognition and more.", "*What you'll do: You will analyse client behaviour and develop targeted communication strategies.", "*What you'll do: You will support the implementation of a reliable and performant data infrastructure that integrates with internal and 3rd party tools.", "*What you'll do: You will be working on credit risk and fraud detection problems.", "*What you'll do: You will be working on real-time recommendation for the Sponsored Product and Campaign advertisements.", "*What you'll do: You will design, develop, and operate data pipelines that form the single source of truth for information regarding Zalando's business processes.", "*What you'll do: You will be participating in the full development life cycle in the transactional domain.", "*What you'll do: You will work on developing technologies, calibration methodologies and prototype instrumentation for the calibration and validation of Appleâ\x80\x99s products.", "*What you'll do: You will build and ensure that all workflows adhere to best practices in terms of data governance, data security, and data quality assurance.", "*What you'll do: You will research and implement state of the art methods in one of our target disciplines (recommendations, ranking, NLP, computer vision).", "*What you'll do: You will be working on development and optimization of innovative pricing models that go beyond existing solutions.", "*What you'll do: You will maintain and improve data applications that help to optimize TeamViewer products, optimize processes in the data warehouse.", "*What you'll do: You will be a core part of the Amadeus data platform working data volumes up to 100k events/second, which should be processed in near real-time.", "*What you'll do: You will build pipelines to extract data from our event-driven application into AWS Data Lake, and build data-driven features for epilot users.", "*What you'll do: You will be working on tailoring content for each individual customer.", "*What you'll do: You will be working on implementing prediction models within our research-driven software framework to cater for the increasing scale and load.", "*What you'll do: You will ensure the optimal allocation of budget across commercial actions.", "*What you'll do: You will work on ML models to predict user behaviour, and/or optimise in-app retention and campaign distribution."]
-------------------
[['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Spark, SQL', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch, TensorFlow', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch, TensorFlow', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Tableau', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS, Airflow', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Scala, AWS, Hadoop', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, R, SQL,', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Spark, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Airflow, Terraform', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS, Databricks', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Scala', 'Hybrid'], ['Herzogenaurach, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Spark', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Power BI, Python, SQL', 'On-site only'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS, Databricks', 'Hybrid'], ['Kleinmachnow, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Spark', 'Hybrid'], ['Hamburg, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Looker', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Scala, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Scala, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS, Databricks', 'Hybrid'], ['DÃ¼sseldorf, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Spark', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Looker', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL', 'Hybrid'], ['DÃºsseldorf, DE', 'Visa sponsorship', 'in English', 'Python, BigQuery, Kafka', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch, PySpark', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Scala, Spark, AWS', 'Hybrid'], ['Kleinmachnow, DE', 'Visa sponsorship', 'in English', 'Python, Spark, PyTorch', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Snowflake, SQL, Tableau', 'On-site only'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Snowflake', 'Remote'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Java, SQL, Data Vault 2.0', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Spark, Databricks, Airflow, MPP DW', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, C++, PyTorch, Tensorflow', 'Remote'], ['DE', 'Visa sponsorship', 'in English', 'Python, C++, Spark', 'Remote'], ['Berlin, DE', 'Apply from abroad', 'in English', 'GCP, Airflow, Spark, Terraform, ks8', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Clickhouse, Kubernetes', 'Remote'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Airflow, AWS, Terraform, Python, SQL', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Spark, Airflow, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'SQL, Hadoop, Google Cloud', 'Hybrid'], ['Stuttgart, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch, PySpark, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'MPP, Python, AWS, Airflow', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, AWS', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Databricks, Spark, Airflow, Kubernetes', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'SQL, Python, Java, AWS, Kubernetes', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, C++, Rust', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, Spark, SQL, Databricks', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, Tensorflow, AWS', 'Hybrid'], ['Munich, DE', 'Visa sponsorship', 'in English', 'Python, SQL', 'Hybrid'], ['GÃ¶ppingen, DE', 'Visa sponsorship', 'in English', 'SQL, BigQuery', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Scala, Spark, Kafka', 'Hybrid'], ['Cologne, DE', 'Visa sponsorship', 'in English', 'Python, SQL, Airflow', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, PyTorch', 'Hybrid'], ['Dortmund, DE', 'Visa sponsorship', 'in English', 'Python, PySpark, PyTorch', 'Hybrid'], ['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, SQL, PyMC', 'Hybrid'], ['Hamburg, DE', 'Visa sponsorship', 'in English', 'Python, R / SQL, AWS', 'Hybrid']]

In [38]:
import pandas as pd
df = pd.DataFrame(columns = ['company_name','job_name','job_desc','job_req_and_info'])

In [39]:
df['company_name'] = company_names
df['job_name'] = job_names
df ['job_desc'] = job_descs
df['job_req_and_info'] =job_infos

In [40]:
df

,company_name,job_name,job_desc,job_req_and_info
0,Get Your Guide,"Senior Data Analyst, Business Analytics (Suppl...",*What you'll do: You will be focusing on uncov...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
1,Amazon,"Applied Scientist (MT), ASIN Localization",*What you'll do: You will focus on delivering ...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
2,Autodesk,AI Research Scientist,*What you'll do: You will be doing fundamental...,"[Munich, DE, Visa sponsorship, in English, Pyt..."
3,Tesla,Data Analyst Supply Chain (m/w/d) - Gigafactory,*What you'll do: You will be working on delive...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
4,Zalando,Data Engineer - Partner Tech,*What you'll do: You will support the implemen...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
...,...,...,...,...
56,epilot,Senior Data Engineer,*What you'll do: You will build pipelines to e...,"[Cologne, DE, Visa sponsorship, in English, Py..."
57,Zalando,Senior Applied Scientist,*What you'll do: You will be working on tailor...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
58,Zalando,Senior Applied Scientist,*What you'll do: You will be working on implem...,"[Dortmund, DE, Visa sponsorship, in English, P..."
59,Zalando,Applied Scientist (Marketing Intelligence),*What you'll do: You will ensure the optimal a...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
60,adjoe,Senior Data Scientist,*What you'll do: You will work on ML models to...,"[Hamburg, DE, Visa sponsorship, in English, Py..."

In [41]:

def turn_to_string(input):
    result_string = ' '.join(input)
    print(result_string)
    return result_string



        
#turn_to_string(['Berlin, DE', 'Visa sponsorship', 'in English', 'Python, PyTorch, TensorFlow', 'Hybrid'])
df['job_req_and_info'] = df['job_req_and_info'].apply(turn_to_string)

Berlin, DE Visa sponsorship in English Python, Spark, SQL Hybrid
Berlin, DE Visa sponsorship in English Python, PyTorch, TensorFlow Hybrid
Munich, DE Visa sponsorship in English Python, PyTorch, TensorFlow Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Tableau Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, AWS, Airflow Hybrid
Berlin, DE Visa sponsorship in English Python, Scala, AWS, Hadoop Hybrid
Berlin, DE Visa sponsorship in English Python, R, SQL, Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Spark, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Airflow, Terraform Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, AWS, Databricks Hybrid
Berlin, DE Visa sponsorship in English Python, Scala Hybrid
Herzogenaurach, DE Visa sponsorship in English Python, SQL, Spark Hybrid
Berlin, DE Visa sponsorship in English Python, SQL Hybrid
Berlin, DE Visa sponsorship in English Python, SQL Hybrid
Munich, DE Visa sponsorship in English Power BI, Python, SQL On-site only
Berlin, DE Visa sponsorship in English Python, SQL, AWS, Databricks Hybrid
Kleinmachnow, DE Visa sponsorship in English Python, SQL, Spark Hybrid
Hamburg, DE Visa sponsorship in English Python, SQL, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Looker Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Scala, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Scala, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, AWS, Databricks Hybrid
DÃ¼sseldorf, DE Visa sponsorship in English Python, SQL, Spark Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Looker Hybrid
Berlin, DE Visa sponsorship in English Python, SQL Hybrid
DÃºsseldorf, DE Visa sponsorship in English Python, BigQuery, Kafka Hybrid
Berlin, DE Visa sponsorship in English Python, PyTorch, PySpark Hybrid
Berlin, DE Visa sponsorship in English Python, Scala, Spark, AWS Hybrid
Kleinmachnow, DE Visa sponsorship in English Python, Spark, PyTorch Hybrid
Berlin, DE Visa sponsorship in English Snowflake, SQL, Tableau On-site only
Berlin, DE Visa sponsorship in English Python, SQL, Snowflake Remote
Munich, DE Visa sponsorship in English Python, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL Hybrid
Berlin, DE Visa sponsorship in English Python, Java, SQL, Data Vault 2.0 Hybrid
Berlin, DE Visa sponsorship in English Spark, Databricks, Airflow, MPP DW Hybrid
Berlin, DE Visa sponsorship in English Python, C++, PyTorch, Tensorflow Remote
DE Visa sponsorship in English Python, C++, Spark Remote
Berlin, DE Apply from abroad in English GCP, Airflow, Spark, Terraform, ks8 Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, Clickhouse, Kubernetes Remote
Munich, DE Visa sponsorship in English Airflow, AWS, Terraform, Python, SQL Hybrid
Munich, DE Visa sponsorship in English Python, PyTorch Hybrid
Berlin, DE Visa sponsorship in English Python, Spark, Airflow, AWS Hybrid
Berlin, DE Visa sponsorship in English SQL, Hadoop, Google Cloud Hybrid
Stuttgart, DE Visa sponsorship in English Python, PyTorch Hybrid
Berlin, DE Visa sponsorship in English Python, PyTorch, PySpark, AWS Hybrid
Berlin, DE Visa sponsorship in English MPP, Python, AWS, Airflow Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, AWS Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, AWS Hybrid
Berlin, DE Visa sponsorship in English Databricks, Spark, Airflow, Kubernetes Hybrid
Berlin, DE Visa sponsorship in English SQL, Python, Java, AWS, Kubernetes Hybrid
Munich, DE Visa sponsorship in English Python, C++, Rust Hybrid
Berlin, DE Visa sponsorship in English Python, Spark, SQL, Databricks Hybrid
Munich, DE Visa sponsorship in English Python, Tensorflow, AWS Hybrid
Munich, DE Visa sponsorship in English Python, SQL Hybrid
GÃ¶ppingen, DE Visa sponsorship in English SQL, BigQuery Hybrid
Berlin, DE Visa sponsorship in English Scala, Spark, Kafka Hybrid
Cologne, DE Visa sponsorship in English Python, SQL, Airflow Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, PyTorch Hybrid
Dortmund, DE Visa sponsorship in English Python, PySpark, PyTorch Hybrid
Berlin, DE Visa sponsorship in English Python, SQL, PyMC Hybrid
Hamburg, DE Visa sponsorship in English Python, R / SQL, AWS Hybrid

In [42]:
df

,company_name,job_name,job_desc,job_req_and_info
0,Get Your Guide,"Senior Data Analyst, Business Analytics (Suppl...",*What you'll do: You will be focusing on uncov...,"Berlin, DE Visa sponsorship in English Python,..."
1,Amazon,"Applied Scientist (MT), ASIN Localization",*What you'll do: You will focus on delivering ...,"Berlin, DE Visa sponsorship in English Python,..."
2,Autodesk,AI Research Scientist,*What you'll do: You will be doing fundamental...,"Munich, DE Visa sponsorship in English Python,..."
3,Tesla,Data Analyst Supply Chain (m/w/d) - Gigafactory,*What you'll do: You will be working on delive...,"Berlin, DE Visa sponsorship in English Python,..."
4,Zalando,Data Engineer - Partner Tech,*What you'll do: You will support the implemen...,"Berlin, DE Visa sponsorship in English Python,..."
...,...,...,...,...
56,epilot,Senior Data Engineer,*What you'll do: You will build pipelines to e...,"Cologne, DE Visa sponsorship in English Python..."
57,Zalando,Senior Applied Scientist,*What you'll do: You will be working on tailor...,"Berlin, DE Visa sponsorship in English Python,..."
58,Zalando,Senior Applied Scientist,*What you'll do: You will be working on implem...,"Dortmund, DE Visa sponsorship in English Pytho..."
59,Zalando,Applied Scientist (Marketing Intelligence),*What you'll do: You will ensure the optimal a...,"Berlin, DE Visa sponsorship in English Python,..."
60,adjoe,Senior Data Scientist,*What you'll do: You will work on ML models to...,"Hamburg, DE Visa sponsorship in English Python..."

,company_name,job_name,job_desc,job_req_and_info
0,Get Your Guide,"Senior Data Analyst, Business Analytics (Suppl...",*What you'll do: You will be focusing on uncov...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
1,Amazon,"Applied Scientist (MT), ASIN Localization",*What you'll do: You will focus on delivering ...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
2,Autodesk,AI Research Scientist,*What you'll do: You will be doing fundamental...,"[Munich, DE, Visa sponsorship, in English, Pyt..."
3,Tesla,Data Analyst Supply Chain (m/w/d) - Gigafactory,*What you'll do: You will be working on delive...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
4,Zalando,Data Engineer - Partner Tech,*What you'll do: You will support the implemen...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
...,...,...,...,...
56,epilot,Senior Data Engineer,*What you'll do: You will build pipelines to e...,"[Cologne, DE, Visa sponsorship, in English, Py..."
57,Zalando,Senior Applied Scientist,*What you'll do: You will be working on tailor...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
58,Zalando,Senior Applied Scientist,*What you'll do: You will be working on implem...,"[Dortmund, DE, Visa sponsorship, in English, P..."
59,Zalando,Applied Scientist (Marketing Intelligence),*What you'll do: You will ensure the optimal a...,"[Berlin, DE, Visa sponsorship, in English, Pyt..."
60,adjoe,Senior Data Scientist,*What you'll do: You will work on ML models to...,"[Hamburg, DE, Visa sponsorship, in English, Py..."